version: '3.8'

services:
  database:
    image: postgres
    container_name: appointment_scheduler_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appointments
    ports:
      - '5432:5432'